# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f1ba86f20a4b26a1a336a06e7a55e460039eed349e3f1a73933b1b8cd0786a06aac79ac7b89ee0cb4463a73a1d55b7c36229020166acfe26889f48ec19a23d4

test:
  secret_key_base: 4b0150de33ecfc629ab66665270a1e31d5969cabdfffb0a4d6d4a5a8285caa445bb1a85a694b8b3e770765961c17de061af56ecadfbdbf9e7b128d25396fd599

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
